### ISSUE TITLE
After installing new 2048 certificate getting (500) Internal Server Error

### ISSUE THREAD

**Issue by alek1111** [paypal/sdk-core-dotnet#54] opened 2017-10-16 16:23 UTC
> Workarounds: NVP/SOAP Signature Credentials

### General information

[response.txt](https://github.com/paypal/PayPal-NET-SDK/files/1384213/response.txt)

* SDK/Library version: v1.7.1
* Environment: Sandbox
* `PayPal-Debug-ID` values: none
* Language, language version, and OS: .Net 4.0 on Windows 7 pro, sp1
[response.txt](https://github.com/paypal/sdk-core-dotnet/files/1388242/response.txt)

### Issue description
Hello, I downloaded new API certificate 2048, encrypted, registered with IIS and since then I get "(500) Internal Server Error." as soon as I do the the 1st call to Paypal API. SetExpressCheckout in this case.
This exact same code and SDK works with older certificate fine. Here is the response I get from Paypal. Thanks!

Forgot to mention we use SOAP APIs.

**Comment by alek1111** [comment] 2017-10-16 20:54
No, I don't have a debug-id, API response is empty

**Comment by alek1111** [comment] 2017-10-19 13:59
@xiaoleih41 Do you guys have any updates on this? Can this be fixed in the nearest release? Thanks!

**Comment by xiaoleih41** [comment] 2017-10-19 14:31
I will check and make sure.

**Comment by xiaoleih41** [comment] 2017-10-19 14:36
This SDK is pretty old and we are deprecating soap/nvp APIs at this time. I will check and get back to you on this.

**Comment by xiaoleih41** [comment] 2017-10-23 15:46
We took a look at your code and suspect that it might have been caused by the setup for the specific environment.  Can you take a look at your verbose logs and check if your server has the capacity to use the certificate?

**Comment by alek1111** [comment] 2017-10-24 22:31
@xiaoleih41 I don't see anything obvious in the logs. Here it is 
[System.Net.trace.log](https://github.com/paypal/sdk-core-dotnet/files/1412711/System.Net.trace.log)

**Comment by xiaoleih41** [comment] 2017-10-25 16:11
Can you please remove the account specific info? I cannot address account specific question unfortunately on a public forum.  Please contact www.paypal-techsupport.com and they will help you troublehshoot the account specific issue.

**Comment by alek1111** [comment] 2017-10-25 16:29
Sure, I removed it, it's sandbox anyway I have contacted them already and they referred me here. I don't think it is account specific issue, I created a brand new sandbox account and it is acting the same way.

**Comment by xiaoleih41** [comment] 2017-10-25 16:30
what's the ticket number. I will have them follow up.

**Comment by alek1111** [comment] 2017-10-25 16:32
171012-000173

**Comment by alek1111** [comment] 2017-10-25 21:35
Do I need to open another ticket with them? This one shows closed and doesn't let me modify it.

**Comment by xiaoleih41** [comment] 2017-10-26 18:39
No need. They have cloned the ticket and will reach out today.

**Comment by pp-randy** [comment] 2017-11-30 22:39
Reopening to do further research into this issue.

**Comment by pp-randy** [comment] 2017-12-13 14:45
This issue has been escalated internally, I apologize for the delay.

**Comment by pp-randy** [comment] 2017-12-13 16:50
@alek1111 my tests are working now.  Did you get your pem converted to p12 successfully?

**Comment by alek1111** [comment] 2017-12-14 23:07
@pp-randy I think it was successful. I can recreate. Do I need to update the SDK?
Thanks!

**Comment by alek1111** [comment] 2017-12-14 23:24
@pp-randy Yes, I just recreated it. Same thing.

**Comment by pp-randy** [comment] 2017-12-15 14:44
I have escalated the error you have provided for further research, it looks like the SDK is handling the certificate fine.  Also in my testing if the cert is not valid you can't create the full connection to the endpoint since it checks for the cert.   

The SDK version you show seems to be the latest version. 

If this impacts your live integration I would advise a switching to a signature credential as a temporary workaround.   I value your time, but since I can't reproduce this are you willing in trying a new certificate just to rule out any issues during the creation process?  Also what is the sandbox account so I can review it?

**Comment by alek1111** [comment] 2017-12-15 15:10
@pp-randy Sandbox is agvozdev-facilitator@collectionsetc.com

I recreated and re-imported certificate, was that what you wanted me to do? 

I'm still getting the same error when trying to connect.

**Comment by pp-randy** [comment] 2017-12-15 15:12
How are you converting the pem from your account to a p12?

**Comment by pp-randy** [comment] 2017-12-15 15:13
Also I've added a second api cert to your account, will you give it a go?  It should be the 12/15/2020 expiration date or the bottom certificate.

**Comment by alek1111** [comment] 2017-12-15 16:47
I'm using PKCS12 tool to convert.

I downloaded the 12/15 certificate and converted, it still bombs with the same error

**Comment by pp-randy** [comment] 2017-12-15 16:52
I used openssl as shown here https://www.paypal.com/us/selfhelp/article/how-do-i-convert-my-pem-format-certificate-to-pkcs12-as-required-by-the-java-and-.net-sdks-ts1020/1

**Comment by alek1111** [comment] 2017-12-15 17:01
@pp-randy Wait. I went to IIS and removed other certificates and made sure only yours stayed registered and it worked! 
Is it something different about your pem file? It looks a little smaller.
Yes I meant I was always using this openssl utility to convert

**Comment by alek1111** [comment] 2017-12-15 17:15
Right, I just tested, as soon as I switch back to 10/23 certificate it stops working.

**Comment by pp-randy** [comment] 2017-12-15 17:29
You can remove your 10/23 certificate and fully create a new one if want to rule out any possible issues.  The cert I added should be 2048 but I don't have a way to actually review it, only add generate it on your account.

**Comment by alek1111** [comment] 2017-12-15 18:01
Yep, I generated a new one, converted it and it works great! Thanks!

I did it a couple of times at least back in October, I swear.

**Comment by pp-randy** [comment] 2017-12-15 18:26
You shouldn't have needed to do that, but as I suspect there might have been an issue in October when the certificate was generated.  Since things are working for you now I will close the issue.  I appreciate your patience while we worked through this.

**Closed by pp-randy** 2017-12-15 18:26 UTC
Labels: bug, question
